### ISSUE TITLE
CAN_83K3BPS for 8MHz not defined

### ISSUE THREAD

**Issue by dartrax** [Seeed-Studio/Seeed_Arduino_CAN#79]
` CAN.begin(CAN_83k3BPS, MCP_8MHz);`
won't work, because in mcp_can.cpp, there is no 83k3BPS case in the select statement for MCP_8MHz.
Also, in mcp_can_dfs.h, 
```
#define MCP_8MHz_83k3BPS_CFG1 (0xxx)
#define MCP_8MHz_83k3BPS_CFG2 (0xxx)
#define MCP_8MHz_83k3BPS_CFG3 (0xxx)
```
is missing.

Probably forgotten at #49

**Comment by Jenkinlu001** [comment]
Thanks for your suggestion, we will add it.

**Comment by ETACSDecoder** [comment]
or
#define MCP_8MHz_83k3BPS_CFG1 (0x01)
#define MCP_8MHz_83k3BPS_CFG2 (0xbe)
#define MCP_8MHz_83k3BPS_CFG3 (0x07)

**Comment by Pillar1989** [comment]
If you feel you need to continue the discussion, you can reopen the issues.

**Comment by J-Dunn** [comment]
```
#define MCP_8MHz_100kBPS_CFG1 (0x01)
#define MCP_8MHz_100kBPS_CFG2 (0xb4)
#define MCP_8MHz_100kBPS_CFG3 (0x06)

#define MCP_8MHz_80kBPS_CFG1 (0x01)
#define MCP_8MHz_80kBPS_CFG2 (0xbf)
#define MCP_8MHz_80kBPS_CFG3 (0x07)

```

How was this closed as "completed". That baudrate still does not exist for 8MHz clock. 

I'm unsure whether this is even possible since the register config is quite complex. 
If it is not possible this should be explained and closed as can't fix, not as completed. 

Can someone who is up to speed on this comment?
TIA.

**Comment by baorepo** [comment]
I opened PR #156 to add the missing MCP2515 8MHz + 83.3kbps support and included a regression test.

@dartrax @J-Dunn If either of you still has hardware using CAN.begin(CAN_83k3BPS, MCP_8MHz);, could you please test this branch/PR and report whether initialization and bus traffic behave correctly on your setup?

**Comment by J-Dunn** [comment]
Unfortunately I don't have a working canbus setup to test this on. 
I needed to test this baud rate as a possibility on an under test system and was surprised to see it was missing. 
This forced me to go through the doc and work it out from first principals and this is the same config I came up with. In the end, it turned out to be quite a simple change, so I have a high degree of confidence it is correct.
