### ISSUE TITLE
Canbus reading from a contactless clip

### ISSUE THREAD

**Issue by ssstofff** [Seeed-Studio/Seeed_Arduino_CAN#85]
i was wondering if it is also possible to read canbus data with this shield not connected to the odb2 but with a contactless clip (eg cancrocodile) on the C-H and C-L cable?

**Comment by wdross** [comment]
I can't tell what the output cable of that cancrocodile product *is*: could be proprietary and you need to purchase their hardware in order to decode it,
OR
It is straight-up CAN and you would be able to utilize CAN_BUS_Shield to read the messages.
Need more information on the output of the cancrocodile...
